project:
  type: website
  output-dir: docs

website:
  title: "Lore Abad"
  navbar:
    left:
      - href: index.qmd
        text: Posts
      - about.qmd
  twitter-card:
    creator: "@loreabad6"
    site: "@loreabad6"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
