---
title: "Presentations and Workshops"
---

## 2024
Vector data cubes for features evolving in space and time. 05.06.2024. Short Paper presentation, AGILE 2024, Glasgow, UK. [Slides](https://loreabad6.github.io/vdc-space-time-feats/presentation/agile24.html#/title-slide) | [Conference paper](https://doi.org/10.5194/agile-giss-5-16-2024) | [Reproducible code and showcase notebook](https://github.com/loreabad6/vdc-space-time-feats?tab=readme-ov-file)

Introduction to R for the Geosciences. 17.04.2024. Short Course, EGU General Assembly 2024, Vienna, Austria. [Website](https://meetingorganizer.copernicus.org/EGU24/session/49442) | [Material](https://loreabad6.github.io/egu24-sc-R4geosciences/)

Geomorphic landform monitoring with raster and vector data cubes. 16-04-2024, EGU General Assembly 2024, Vienna, Austria. [Abstract](https://doi.org/10.5194/egusphere-egu24-10019) | [PDF Poster](https://research.uni-salzburg.at/ws/portalfiles/portal/35239558/EGU24_AbadL_Poster_BetterLandscape.pdf) | [HTML Poster](https://loreabad6.github.io/posters/EGU24/EGU24-poster-betterland.html)

## 2023

Spatial Data Science across Languages (SDSL). 19-19.09.2023. Workshop organized by NFDI4Earth and ifgi, University of Munster,  Münster, Germany. [Website](https://r-spatial.org/sdsl/)

Tools and packages to query and process Sentinel-1 and Sentinel-2 data with R and Python. 31-08-2023. OpenGeoHub Summer School Poznan 2023, Poznan, Poland. [Material](https://loreabad6.github.io/ogh23/) | [Video](https://doi.org/10.5446/63365)

Open data and open science for risk, hazard and climate assessments. 30-08-2023. Discussion Forum "What can R, Python, and Julia development communities do to combat the climate crisis?". OpenGeoHub Summer School Poznan 2023, Poznan, Poland. [Video](https://youtu.be/qiUh9WjozRA)

Expert-based and data-driven gully and cliff erosion feature detection in New Zealand. 15-07-2023, 28th IUGG General Assembly, Berlin, Germany. [Abstract](https://doi.org/10.57757/IUGG23-0228) | [Poster](https://research.uni-salzburg.at/ws/portalfiles/portal/32837631/IUGG23_AbadL_Poster_BetterPortrait.pdf)

Gully and cliff erosion feature detection in the Wairoa catchment in Hawke’s Bay, New Zealand. 26-04-2023, EGU General Assembly 2023, Vienna, Austria. [Abstract](https://doi.org/10.5194/egusphere-egu23-1468) | [Poster](https://uni-salzburg.elsevierpure.com/files/30166446/EGU23_AbadL_Poster_v2_compressed.pdf)

## 2022

Mass movement susceptibility assessment of alpine infrastructure in the Salzkammergut area, Austria. 18-10-2022. Landslide Scientific Assessment Conference: Landslide hazard, (online). [Video](https://www.youtube.com/watch?v=96H3rLHHazo&ab_channel=LandScient)

SliDEM: An open-source-based workflow for DEM generation from Sentinel-1 for landslide volume estimation. 26-08-2022. FOSS4G 2022 - Workshop. Florence, Italy. [Slides](https://drive.google.com/file/d/1tc5K_Rwd8wFz1pvrpZXZ7StEUtlCWMeJ/view) | [Conference paper](https://doi.org/10.5194/isprs-archives-XLVIII-4-W1-2022-5-2022) | [Software](https://github.com/SliDEM-project/SliDEM-python)

sfnetworks: Tidy Geospatial Networks in R. 22-08-2022. FOSS4G 2022 - Workshop. Florence, Italy. [Slides](https://sfnetworks.github.io/foss4g-workshop/slides/slides)

Análisis de redes espaciales con `sfnetworks`. 17-08-2022. OceanHackWeek 2022 (online). [Slides](https://sfnetworks.github.io/ohw22-es/sfnetworks-es) | [Video](https://youtu.be/G6nTyJZI2tU?feature=shared)

Análisis de redes espaciales con `sfnetworks`. 08-06-2022. R-Ladies Guayaquil Meetup. Guayaquil, Ecuador (online). [Slides](https://sfnetworks.github.io/rladies-gye/slides) | [Video](https://www.youtube.com/watch?v=Av5lhO3Fero&ab_channel=R-LadiesEcuador)

Exploring knowledge-based and data-driven approaches to map earthflow and gully erosion features in New Zealand. 27-05-2022. EGU General Assembly 2022, Vienna, Austria (online). [Abstract](https://doi.org/10.5194/egusphere-egu22-1013) 

An open-source Python package for DEM generation and landslide volume estimation based on Sentinel-1 imagery. 24-05-2022. EGU General Assembly 2022, Vienna, Austria (online). [Abstract](https://doi.org/10.5194/egusphere-egu22-693) | [Slides](https://presentations.copernicus.org/EGU22/EGU22-693_presentation-h520626.pdf)

## 2021

Reproducible spatial data visualization with R. R-Spatial Panel. 30-09-2021. FOSS4G 2021, Buenos Aires, Argentina (online). [Slides](https://loreabad6.github.io/foss4g/slides.html#1) | [Video](https://youtu.be/iA0OQ2Icn6Y)

Road Construction and Rainfall as Landslide Triggers in the Rio Lucma Catchment, Eastern Cordillera Blanca, Peru. 29-04-2021. EGU General Assembly 2021, Vienna, Austria (online). [Abstract](https://meetingorganizer.copernicus.org/EGU21/EGU21-11015.html) |  [Slides](https://loreabad6.github.io/vEGU21_display/display.html#1)

Introducción al paquete sfnetworks: Análisis de redes geoespaciales con R. 15-01-2021. R-Espacial en Español, (online). [Slides](https://sfnetworks.github.io/sfnetworks-REspacialES/slides#1) | [Video](https://www.youtube.com/watch?v=jKRmsOjguqo&ab_channel=REspacialenEspa%C3%B1ol)

## 2020

Mapping and monitoring landslide-dammed lakes in Kaikōura, New Zealand using the Google Earth Engine. 21-10-2020. Geo For Good User Summit 2020 - Public Sector Meetup (online). [Slides](https://qrgo.page.link/izjEp) | [Poster](https://docs.google.com/presentation/d/1FVrxwwuBUsb69OKYbyssNDphket-6V4nhlK1OuXVDdw) | [Video](https://www.youtube.com/live/CbHYkUpCwCI?feature=shared&t=3035)

Bicycle Network Analysis for assessing cyclability. 24-09-2020, Cycling Potential Hackathon: Lisbon (online). [Slides](https://loreabad6.github.io/bna-presentation/bna-presentation.html#1)

El rol de las tecnologías geoespaciales para el mapeo y monitoreo de peligros naturales. 19-09-2020, Voces de la  Ingeniería Ambiental, Cuenca, Ecuador (online).  [Slides](https://loreabad6.github.io/VocesAmbiental/presentacion.html) | [Video](https://www.facebook.com/watch/live/?extid=MZJv41PQtCQ5l6jT&ref=watch_permalink&v=327432258323373)

Implementing geo citizen science solutions: experiences from the citizenMorph project. 09-07-2020, GI_Forum 2020: connecting spatially – virtually, Salzburg, Austria (online).

Tidy Geospatial Networks in R: Introducing the sfnetworks package. 16-06-2020. e-Rum2020 satellite event: Hackathon on Spatial Networks, (online). [Slides](https://www.youtube.com/watch?v=ZXTNXsvKYwo&ab_channel=RobinLovelace) | [Video](https://www.youtube.com/watch?v=ZXTNXsvKYwo&ab_channel=RobinLovelace)

Mapping and monitoring of landslide-dammed lakes using Sentinel-2 time series. 07-05-2020. EGU General Assembly 2020, Vienna, Austria (online).
[Abstract](https://meetingorganizer.copernicus.org/EGU2020/EGU2020-572.html) | [Slides](https://presentations.copernicus.org/EGU2020/EGU2020-572_presentation.pdf)

## 2018

Bike Network Analysis in Lisbon. 12-06-2018, Open Data for Open Cities v 2.0 - AGILE 2018 Workshop, Lund Sweden. [Slides](https://drive.google.com/file/d/1yBzFEb9vSe3ScHxAb-rcWuBYAPYDZpet/view?usp=sharing)

## 2017
Exploring Space-Time Patterns Of Volunteered Cycling Data In An Intermediate City. 11-11-2017, Geomundus 2017, Münster, Germany.
